### ISSUE TITLE
Is it possible to move navigation arrows out of slider box?

### ISSUE THREAD

**Issue by Stromwerk** [zefoy/ngx-swiper-wrapper#234]
Would it be possible to make the arrows appear outside of the main swiper slider, as in my use case having the navigation arrows inside would cause quite a few missclicks trough one of the items on the slider.

Thank you for the amazing library and angular wrapper!

**Comment by sconix** [comment]
Yes its perfectly possible. Just have a custom arrows placed where you want them and tell Swiper their classes. So just have a look at Swiper documentation how to configure Swiper.

**Comment by Stromwerk** [comment]
Thank you, this worked for me. However now I added a wrapper element for the swiper so I can set some padding, but this makes the swiper move and overflow it's container.

This is my code

```html
<mat-card>
    <h1>My Airlines</h1>
    <div class="swiper-wrapper">
        <swiper #airlinesSlider [config]="twoSlideConfig">
            <div *ngFor="let twoAirlines of groupedAirlines">
                <div class="img-wrapper" *ngFor="let airline of twoAirlines">
                    <img src="{{ airline.blogo ? 'data:image/png;base64,' + airline.blogo : 'assets/images/no-image.jpg' }}"
                        (click)="openMyAirlines(airline)">
                </div>
            </div>
        </swiper>
        <button mat-icon-button class="arrow-prev">
            <mat-icon>chevron_left</mat-icon>
        </button>
        <button mat-icon-button class="arrow-next">
            <mat-icon>chevron_right</mat-icon>
        </button>
    </div>
</mat-card>
```

```scss
.swiper-wrapper {
    padding: 0 50px;
    position: relative;
}

.arrow-prev, .arrow-next {
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
}

.arrow-prev {
    left: 0;
}

.arrow-next {
    right: 0;
}
```

This is what the wrapper div looks like
![image](https://user-images.githubusercontent.com/11208509/62697910-1a7f3a00-b9dc-11e9-9866-a48356c3a10a.png)
