### ISSUE TITLE
ChangeDetection Issue?

### ISSUE THREAD

**Issue by picosam** [zefoy/ngx-swiper-wrapper#33]
Hello, I have a very strange problem. I have a smart component where I set `changeDetection: ChangeDetectionStrategy.OnPush`. Inside it, I use the swiper, that holds another component for each one of its slides simply to generate a set of URIs for responsive images:

```css
.photo {
	width: 100vw !important;
	@media (min-width: 576px) {
		width: 540px !important;
	}
	@media (min-width: 768px) {
		width: 300px !important;
	}
	@media (min-width: 992px) {
		width: 400px !important;
	}
	@media (min-width: 1200px) {
		width: 475px !important;
	}
}
```
```typescript
<swiper class="d-flex photo mw-100" [config]="SWIPER_CONFIG">
    <responsive-image class="w-100" *ngFor="let photo of users[userIndex].photos">
    </responsive-image>
</swiper>
```

The issue is, when the user clicks on a certain button in the parent component that sets `userIndex` above to a different number, the photos do change, but they suddenly appear all next to each other, not respecting the correct width. Even funnier, it only takes another click on the same button (that simply calls the same `setUserIndex` function again ) for the swiper to show the images correctly again!

Do you have any idea what's happening please? I did try to manually use `markForChanges()` and to switch the photos above by an `Observable` with no success. Of course if I remove the change detection strategy above everything works well.
